### ISSUE TITLE
预览是黑色主题而打印是白色主题

### ISSUE THREAD

**Issue by SweetPastry** [Soanguy/MPE_Soanguy#1]
项目结构大致为
```
|--style.less
|--assets
|--homework--|--作业1.md
             |--作业1.pdf
```

预览的时候是黑色主题,而打印的时候是白色主题. 这个我不太懂怎么设置, 比如如果我想打印黑色主题预览白色主题的话应该怎么操作, 感谢.
![image](https://github.com/user-attachments/assets/617815c3-2fb3-4d6e-9bbc-3b2f63593152)
![image](https://github.com/user-attachments/assets/51017c19-ad70-40cc-969b-d56a2c3af23c)
顺带一提, 我注释掉了style.less文件中关于目录的设置, chrome打印会在pdf头多出一个空白页,prince打印会多出两页马,其中第一页右上角有prince的icon,即使不注释关于目录的设置也会出现这个情况.

**Comment by Soanguy** [comment]
抱歉這麼久才回覆。

我好久沒修改過了，記得不是很清楚：
   MPE 使用 less 文件來進行樣式設定，調整之後，還需要生成對應的 css 才可以。
   可以使用 [Compile Hero Pro](https://marketplace.visualstudio.com/items?itemName=Wscats.eno) 
   這個插件來自動生成對應的 css 文件。

關於修改打印背景：
   找到 /assets/print_setting.less 這個文件，裡面有修改背景的相關設定。
   具體如下：

```
   @media print {
    :root {
        --bg-body: #fff; # 修改這個顏色可以控制正文區域的背景色；
          }
   @page  {
        background-color: #fff; # 需要新增這個 background-color 屬性，調整他可以控制頁面背景色。
          }
```

修改完成後，返回 style.less 文件，保存生成 style.css 文件就可以控制打印背景色了。

**Comment by Soanguy** [comment]
關於目錄的問題，如果有一個 簡單的示例 的話，可能會好一點。

關於 prince icon 的問題，是自動生成的。
但根據官方的提示，該圖標不會影響打印。
如果在觀感上不適的話，可以使用 PDF 編輯器去除。

**Comment by Soanguy** [comment]
觀察你的貼圖，是通過導入的方式設定主題的。這樣有一些麻煩。

MPE 自身帶有切換主題的選單，可以將選擇主題 none
<img width="401" alt="image" src="https://github.com/user-attachments/assets/2ab2c15a-5431-43d2-89aa-f7955f2eeba2">

同時，使用 cmd-shift-p 運行 Markdown Preview Enhanced: Customize CSS (Global) 
打開默認的文件樣式文件，然後在文件管理器中打開，把本主題的文件一併複製到這個文件夾下面就可以了。
<img width="629" alt="image" src="https://github.com/user-attachments/assets/3bf3765d-5695-468a-8599-9902390bbc4f">

如果你在使用其他 MPE 的主題的話，也可以使用相同的方式來設置默認的主題（也就是 none）。

**Comment by Soanguy** [comment]
對，忘記了還有預覽背景。預覽背景只需要修改：assets/root_setting.less 中的：

```
  :root {--bg-body: var(--theme-color-3);}
```

之後保存 root_setting.less 和 style.less，重新生成 style.css 即可。

一些相關的顏色、背景、字體、行高的元素都可以在 root_setting.less 中找到，修改對應的部分就可以。
